"""
Synthetic broker exports.

`pure_noise` is the marketing asset: trades with zero true edge, generated by
a coin flip, written in NinjaTrader export format. Run any journal against it
and watch it name your best setup.
"""

from __future__ import annotations

import numpy as np
import pandas as pd

SYMBOLS = ["ES", "NQ", "CL", "GC"]
HOURS = [3, 7, 9, 10, 11, 13, 14, 15, 19, 21]


def _frame(n, rng, pnl, start="2025-01-02"):
    days = pd.bdate_range(start, periods=int(np.ceil(n / 4)) + 5)
    entry = []
    for i in range(n):
        d = days[i // 4]
        h = rng.choice(HOURS)
        entry.append(pd.Timestamp(d) + pd.Timedelta(hours=int(h), minutes=int(rng.integers(0, 60))))
    entry = pd.Series(sorted(entry))
    hold = pd.to_timedelta(rng.integers(2, 240, size=n), unit="m")
    return pd.DataFrame({
        "Instrument": [f"{rng.choice(SYMBOLS)} 03-25" for _ in range(n)],
        "Account": "SIM101",
        "Market pos.": np.where(rng.random(n) < 0.5, "Long", "Short"),
        "Quantity": rng.integers(1, 4, size=n),
        "Entry price": np.round(rng.normal(5000, 40, n), 2),
        "Exit price": np.round(rng.normal(5000, 40, n), 2),
        "Entry time": entry.dt.strftime("%Y-%m-%d %H:%M:%S"),
        "Exit time": (entry + hold).dt.strftime("%Y-%m-%d %H:%M:%S"),
        "Profit": np.round(pnl, 2),
        "Commission": np.round(rng.integers(1, 5, size=n) * 2.09, 2),
    })


def pure_noise(n: int = 400, seed: int = 3) -> pd.DataFrame:
    """Zero true edge. Wins 45% of the time, winners 1.22x the size of losers."""
    rng = np.random.default_rng(seed)
    win = rng.random(n) < 0.45
    pnl = np.where(win,
                   rng.gamma(2.0, 150, n),
                   -rng.gamma(2.0, 150 * 0.45 / 0.55, n))
    pnl = pnl - pnl.mean()  # force expectancy to exactly zero
    return _frame(n, rng, pnl)


def real_edge(n: int = 400, seed: int = 11, edge_r: float = 0.18) -> pd.DataFrame:
    """A genuine, uniform edge — no slice is special, the whole book is."""
    rng = np.random.default_rng(seed)
    win = rng.random(n) < 0.52
    pnl = np.where(win, rng.gamma(2.0, 160, n), -rng.gamma(2.0, 140, n))
    pnl = pnl - pnl.mean() + edge_r * np.abs(pnl).mean()
    return _frame(n, rng, pnl)


def concentrated_edge(n: int = 600, seed: int = 5) -> pd.DataFrame:
    """Flat everywhere except a genuinely profitable morning window."""
    rng = np.random.default_rng(seed)
    df = pure_noise(n, seed=seed)
    hour = pd.to_datetime(df["Entry time"]).dt.hour
    boost = np.where((hour >= 9) & (hour < 11), rng.normal(320, 120, n), 0.0)
    df["Profit"] = np.round(df["Profit"].to_numpy() + boost, 2)
    return df
